version: "3.3"
networks:
   registrations_network:
     external: true
services:
  frontend:
    image: registrations-frontend
    ports:
      - "80:80"
    networks:
      - registrations_network
  db:
    image: postgres
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: reservations
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: iglesiacei
    networks:
      - registrations_network
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=reservations
      - DB_USER=backend
      - DB_PASSWORD=iglesiacei
      - DB_PORT=5432
    networks:
      - registrations_network
    depends_on:
      - db
