# Generated by Django 3.2.5 on 2021-07-03 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255, null=True)),
                ('first_surname', models.CharField(max_length=255, null=True)),
                ('second_surname', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.IntegerField()),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.documenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attended', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.person')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.location'),
        ),
    ]
