# Generated by Django 3.2.5 on 2021-07-03 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(choices=[('PR', 'Padre/Madre'), ('CH', 'Hijo/Hija'), ('SI', 'Hermano/Hermana'), ('GP', 'Abuelo/Abuela'), ('SP', 'Esposo/Esposa'), ('OT', 'Otro')], max_length=2)),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_of', to='registration.person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='registration.person')),
            ],
        ),
    ]
