# Generated by Django 3.2.5 on 2021-07-09 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210705_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='session',
            new_name='event',
        ),
        migrations.AddField(
            model_name='registration',
            name='seat_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='HandWashRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.person')),
            ],
        ),
    ]
