# Generated by Django 3.2.5 on 2021-07-09 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20210709_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 3, 30, 21, 783368)),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_surname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='second_surname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
