# Generated by Django 3.2.5 on 2021-07-09 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20210709_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 5, 37, 41, 303972)),
        ),
    ]
