# Generated by Django 3.2.5 on 2021-07-09 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20210709_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 5, 54, 13, 454951)),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('document_type', 'document_id')},
        ),
    ]
