# Generated by Django 3.2.5 on 2021-07-10 22:58

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20210709_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='label',
            field=models.CharField(default=datetime.datetime(2021, 7, 10, 22, 58, 0, 439286), max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 7, 10, 22, 57, 9, 724727)),
        ),
    ]
