# Generated by Django 3.2.5 on 2021-07-12 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20210712_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 7, 12, 23, 2, 42, 190643)),
        ),
    ]
