# Generated by Django 3.2.5 on 2021-07-13 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_alter_person_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempregistration',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 7, 13, 0, 24, 46, 761992)),
        ),
    ]
