# Generated by Django 3.2.5 on 2021-07-22 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20210713_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 7, 22, 1, 58, 50, 848211)),
        ),
    ]
