# Generated by Django 3.2.5 on 2021-07-22 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_alter_person_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 7, 22, 6, 22, 58, 826543)),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
